// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.iansails.yelp.model;

import com.iansails.yelp.model.Text;

privileged aspect Text_Roo_JavaBean {
    
    public String Text.getText() {
        return this.text;
    }
    
    public void Text.setText(String text) {
        this.text = text;
    }
    
}
