// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.iansails.yelp.model.yelp;

import com.iansails.yelp.model.yelp.YelpSearchResult;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect YelpSearchResult_Roo_Configurable {
    
    declare @type: YelpSearchResult: @Configurable;
    
}
